FirebaseError: Firebase Storage: User does not have permission to access 'event-images/erVwHXI6EDdYfhsVq6JD/good-friday-sunset.jpg'. (storage/unauthorized)